### ISSUE TITLE
configure is not executable

### ISSUE THREAD

**Issue by lkupcsik** [dominodatalab/DominoDataR#21]
I cloned the repository, then after `R CMD INSTALL`, I get the following error:

```
** using staged installation
ERROR: 'configure' exists but is not executable
```

After `chmod u+x ./configure`, the installation proceeds to the next stage

**Comment by ddl-gabrielhaim** [comment]
The configure script was automatically installing the underlying python library which is against CRAN's [policies](https://cran.r-project.org/web/packages/policies.html) (`Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory`). It has been removed in the latest versions of the package.
