### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by datawookie** [dominodatalab/DominoDataR#3]
Hi!

I'd like to suggest changing the repository name to something that doesn't include hyphens.

I'm working on https://github.com/dominodatalab/low-code-assistant-rstudio with @daattali. We'd like to include the `r-domino-data` package as a dependency. However, the hyphens in the repository name are making this a problem. The `DESCRIPTION` file has the following (abridged to only show relevant content):

```
Imports:
    r-domino-data
Remotes:
    dominodatalab/r-domino-data
```

When attempting to install this results in the following error:

```
ERROR: dependency ‘r’ is not available for package ‘assistDomino’
```

I don't think that hyphens are legal in package names, which is why the "r-domino-data" import is being truncated to "r".

How about renaming the repository to `DominoDataR`? Alternatively, maybe `rdominodata` or `dominodatar`? Whichever way, ideally the repository should have the same name as the package and the package name should satisfy all of the requirements on package names.

If, alternatively, you know of another way around the dependency issue then I'd be super keen to know about it. :+1: 

Best regards, Andrew.

**Comment by daattali** [comment]
@datawookie is correct, according to https://cran.r-project.org/doc/manuals/r-devel/R-exts.html :

> ... the name of the package. This should contain only (ASCII) letters, numbers and dot, have at least two characters and start with a letter and not end in a dot

**Comment by ddl-gabrielhaim** [comment]
Thanks for catching this, renamed to `DominoDataR`.

**Comment by datawookie** [comment]
Thanks @ddl-gabrielhaim!
